spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/user-db

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    listener:
      ack-mode: record
      concurrency: 1
      type: single
      missing-topics-fatal: false
      retry:
        enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8086
  error:
    include-message: always

logging:
  level:
    root: INFO
    org.springframework.kafka: DEBUG

websocket:
  endpoint: /ws
  topic: /topic/user-status